### ISSUE TITLE
Photo not working

### ISSUE THREAD

**Issue by xbauquet** [PaulineNS/Instagrid#3]
https://github.com/PaulineNS/Instagrid/blob/29b3f1fd6a9bc8647edd74857ae02568c6e911e0/Instagrid/Controller/ViewController.swift#L26

Here you say that self is the delegate but self does not implement the 2 protocols

**Comment by PaulineNS** [comment]
@xbauquet  I added the 2 protocols to my ViewController Class.. It seems that it still doesn't work
